// <auto-generated />
using System;
using ADAMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123145528_AddFryRecordForegnToFry")]
    partial class AddFryRecordForegnToFry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADAMS.Models.Account", b =>
                {
                    b.Property<int>("AccountSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountSN"));

                    b.Property<int>("AccGroupSN")
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.Property<int?>("TenantSN1")
                        .HasColumnType("int");

                    b.HasKey("AccountSN");

                    b.HasIndex("AccGroupSN");

                    b.HasIndex("TenantSN");

                    b.HasIndex("TenantSN1");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ADAMS.Models.AccountGroup", b =>
                {
                    b.Property<int>("AccountGroupSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountGroupSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("AccountGroupSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("AccountGroup");
                });

            modelBuilder.Entity("ADAMS.Models.Area", b =>
                {
                    b.Property<int>("AreaSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaSN"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GPSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GPSY")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModityTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("AreaSN");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("ADAMS.Models.Authorization", b =>
                {
                    b.Property<int>("AuthorizationSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorizationSN"));

                    b.Property<int>("AccGroupSN")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FunctionSN")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorizationSN");

                    b.HasIndex("AccGroupSN");

                    b.HasIndex("FunctionSN");

                    b.ToTable("Authorization");
                });

            modelBuilder.Entity("ADAMS.Models.Fry", b =>
                {
                    b.Property<int>("FrySN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrySN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FVName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SupplierSN")
                        .HasColumnType("int");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FrySN");

                    b.HasIndex("SupplierSN");

                    b.ToTable("Fry");
                });

            modelBuilder.Entity("ADAMS.Models.FryRecord", b =>
                {
                    b.Property<int>("FryRecordSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FryRecordSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FarmingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FarmingDensity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FarmingNum")
                        .HasColumnType("int");

                    b.Property<int>("FarmingPCS")
                        .HasColumnType("int");

                    b.Property<decimal>("FryAge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FrySN")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManageAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PondArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PondSN")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SurvivalRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TTL_PCS")
                        .HasColumnType("int");

                    b.Property<decimal?>("TTL_Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FryRecordSN");

                    b.HasIndex("FrySN");

                    b.HasIndex("PondSN");

                    b.ToTable("FryRecord");
                });

            modelBuilder.Entity("ADAMS.Models.Function", b =>
                {
                    b.Property<int>("FunctionSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FunctionSN"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShow")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("UpperFunctionSN")
                        .HasColumnType("int");

                    b.HasKey("FunctionSN");

                    b.ToTable("Function");
                });

            modelBuilder.Entity("ADAMS.Models.Pond", b =>
                {
                    b.Property<int>("PondSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PondSN"));

                    b.Property<int>("AreaSN")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GPSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GPSY")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModityTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PondArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PondLength")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PondWidth")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("PondSN");

                    b.HasIndex("AreaSN");

                    b.ToTable("Pond");
                });

            modelBuilder.Entity("ADAMS.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierSN"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierType")
                        .HasColumnType("int");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("SupplierSN");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ADAMS.Models.Tenant", b =>
                {
                    b.Property<int>("SN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResponEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResponPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantAddr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SN");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.Account", b =>
                {
                    b.HasOne("ADAMS.Models.AccountGroup", "AccGroup")
                        .WithMany("Accounts")
                        .HasForeignKey("AccGroupSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Tenant", null)
                        .WithMany("Accounts")
                        .HasForeignKey("TenantSN1");

                    b.Navigation("AccGroup");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.AccountGroup", b =>
                {
                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany("AccountGroups")
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.Authorization", b =>
                {
                    b.HasOne("ADAMS.Models.AccountGroup", "AccountGroup")
                        .WithMany("Authorizations")
                        .HasForeignKey("AccGroupSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Function", "Function")
                        .WithMany("Authorizations")
                        .HasForeignKey("FunctionSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountGroup");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("ADAMS.Models.Fry", b =>
                {
                    b.HasOne("ADAMS.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ADAMS.Models.FryRecord", b =>
                {
                    b.HasOne("ADAMS.Models.Fry", "Fry")
                        .WithMany()
                        .HasForeignKey("FrySN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Pond", "Pond")
                        .WithMany("FryRecords")
                        .HasForeignKey("PondSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fry");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("ADAMS.Models.Pond", b =>
                {
                    b.HasOne("ADAMS.Models.Area", "Area")
                        .WithMany("Ponds")
                        .HasForeignKey("AreaSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ADAMS.Models.AccountGroup", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("ADAMS.Models.Area", b =>
                {
                    b.Navigation("Ponds");
                });

            modelBuilder.Entity("ADAMS.Models.Function", b =>
                {
                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("ADAMS.Models.Pond", b =>
                {
                    b.Navigation("FryRecords");
                });

            modelBuilder.Entity("ADAMS.Models.Tenant", b =>
                {
                    b.Navigation("AccountGroups");

                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
