// <auto-generated />
using System;
using ADAMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204025135_AddHarvestRecordTable")]
    partial class AddHarvestRecordTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADAMS.Models.Account", b =>
                {
                    b.Property<int>("AccountSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountSN"));

                    b.Property<int>("AccGroupSN")
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RealName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("AccountSN");

                    b.HasIndex("AccGroupSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ADAMS.Models.AccountGroup", b =>
                {
                    b.Property<int>("AccountGroupSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountGroupSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("AccountGroupSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("AccountGroup");
                });

            modelBuilder.Entity("ADAMS.Models.Area", b =>
                {
                    b.Property<int>("AreaSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaSN"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GPSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GPSY")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("AreaSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("ADAMS.Models.Authorization", b =>
                {
                    b.Property<int>("AuthorizationSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorizationSN"));

                    b.Property<int>("AccGroupSN")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FunctionSN")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorizationSN");

                    b.HasIndex("AccGroupSN");

                    b.HasIndex("FunctionSN");

                    b.ToTable("Authorization");
                });

            modelBuilder.Entity("ADAMS.Models.Feed", b =>
                {
                    b.Property<int>("FeedSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SupplierSN")
                        .HasColumnType("int");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FeedSN");

                    b.HasIndex("SupplierSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("Feed");
                });

            modelBuilder.Entity("ADAMS.Models.FeedingPlanDetail", b =>
                {
                    b.Property<int>("FPDSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FPDSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FPMSN")
                        .HasColumnType("int");

                    b.Property<decimal>("FP_ABW")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FP_DOC")
                        .HasColumnType("int");

                    b.Property<decimal>("FP_FeedingRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FPDSN");

                    b.HasIndex("FPMSN");

                    b.ToTable("FeedingPlanDetail");
                });

            modelBuilder.Entity("ADAMS.Models.FeedingPlanMain", b =>
                {
                    b.Property<int>("FPMSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FPMSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FVSN")
                        .HasColumnType("int");

                    b.Property<string>("FeedingPlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("FPMSN");

                    b.HasIndex("FVSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("FeedingPlanMain");
                });

            modelBuilder.Entity("ADAMS.Models.FeedingRecord", b =>
                {
                    b.Property<int>("FeedingRecordSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedingRecordSN"));

                    b.Property<decimal>("ABW")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DOC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FeedSN")
                        .HasColumnType("int");

                    b.Property<decimal>("FeedingAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("FeedingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManageAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PondSN")
                        .HasColumnType("int");

                    b.Property<decimal?>("SurvivalRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TimeZoneSN")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FeedingRecordSN");

                    b.HasIndex("FeedSN");

                    b.HasIndex("PondSN");

                    b.HasIndex("TimeZoneSN");

                    b.ToTable("FeedingRecord");
                });

            modelBuilder.Entity("ADAMS.Models.FishVariety", b =>
                {
                    b.Property<int>("FVSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FVSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FVName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FVSN");

                    b.ToTable("FishVariety");
                });

            modelBuilder.Entity("ADAMS.Models.Fry", b =>
                {
                    b.Property<int>("FrySN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrySN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FVSN")
                        .HasColumnType("int");

                    b.Property<string>("FryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SupplierSN")
                        .HasColumnType("int");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FrySN");

                    b.HasIndex("FVSN");

                    b.HasIndex("SupplierSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("Fry");
                });

            modelBuilder.Entity("ADAMS.Models.FryRecord", b =>
                {
                    b.Property<int>("FryRecordSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FryRecordSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FarmingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FarmingDensity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FarmingNum")
                        .HasColumnType("int");

                    b.Property<int>("FarmingPCS")
                        .HasColumnType("int");

                    b.Property<decimal>("FryAge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FrySN")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManageAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PondArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PondSN")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SurvivalRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TTL_PCS")
                        .HasColumnType("int");

                    b.Property<decimal?>("TTL_Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FryRecordSN");

                    b.HasIndex("FrySN");

                    b.HasIndex("PondSN");

                    b.ToTable("FryRecord");
                });

            modelBuilder.Entity("ADAMS.Models.Function", b =>
                {
                    b.Property<int>("FunctionSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FunctionSN"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShow")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("UpperFunctionSN")
                        .HasColumnType("int");

                    b.HasKey("FunctionSN");

                    b.ToTable("Function");
                });

            modelBuilder.Entity("ADAMS.Models.GrowTargetDetail", b =>
                {
                    b.Property<int>("GTDSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GTDSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GTMSN")
                        .HasColumnType("int");

                    b.Property<decimal>("GT_ABW")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("GT_DOC")
                        .HasColumnType("int");

                    b.Property<decimal>("GT_DailyGrow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GTDSN");

                    b.HasIndex("GTMSN");

                    b.ToTable("GrowTargetDetail");
                });

            modelBuilder.Entity("ADAMS.Models.GrowTargetMain", b =>
                {
                    b.Property<int>("GTMSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GTMSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FVSN")
                        .HasColumnType("int");

                    b.Property<string>("GTMName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GTMSN");

                    b.HasIndex("FVSN");

                    b.ToTable("GrowTargetMain");
                });

            modelBuilder.Entity("ADAMS.Models.HarvestRecord", b =>
                {
                    b.Property<int>("HarvestRecordSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HarvestRecordSN"));

                    b.Property<decimal>("ABW")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DOC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("date");

                    b.Property<int>("HarvestPCS")
                        .HasColumnType("int");

                    b.Property<string>("HarvestType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("HarvestWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManageAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PondSN")
                        .HasColumnType("int");

                    b.HasKey("HarvestRecordSN");

                    b.HasIndex("PondSN");

                    b.ToTable("HarvestRecord");
                });

            modelBuilder.Entity("ADAMS.Models.Pond", b =>
                {
                    b.Property<int>("PondSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PondSN"));

                    b.Property<int>("AreaSN")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GPSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GPSY")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PondArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PondLength")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PondNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PondWidth")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("PondSN");

                    b.HasIndex("AreaSN");

                    b.HasIndex("TenantSN");

                    b.ToTable("Pond");
                });

            modelBuilder.Entity("ADAMS.Models.SamplingRecord", b =>
                {
                    b.Property<int>("SamplingRecordSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SamplingRecordSN"));

                    b.Property<decimal>("ABW")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DOC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmingCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManageAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PondSN")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SamplingDate")
                        .HasColumnType("date");

                    b.Property<int>("SamplingPCS")
                        .HasColumnType("int");

                    b.Property<string>("SamplingType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("SamplingWeight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SamplingRecordSN");

                    b.HasIndex("PondSN");

                    b.ToTable("SamplingRecord");
                });

            modelBuilder.Entity("ADAMS.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierSN"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierType")
                        .HasColumnType("int");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.HasKey("SupplierSN");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ADAMS.Models.Tenant", b =>
                {
                    b.Property<int>("SN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResponEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResponPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantAddr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SN");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.TimeZone", b =>
                {
                    b.Property<int>("TimeZoneSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeZoneSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantSN")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZoneNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TimeZoneSN");

                    b.ToTable("TimeZone");
                });

            modelBuilder.Entity("ADAMS.Models.Unit", b =>
                {
                    b.Property<int>("UnitSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitSN"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitSN");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("ADAMS.Models.Account", b =>
                {
                    b.HasOne("ADAMS.Models.AccountGroup", "AccGroup")
                        .WithMany("Accounts")
                        .HasForeignKey("AccGroupSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany("Accounts")
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccGroup");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.AccountGroup", b =>
                {
                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany("AccountGroups")
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.Area", b =>
                {
                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany("Areas")
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.Authorization", b =>
                {
                    b.HasOne("ADAMS.Models.AccountGroup", "AccountGroup")
                        .WithMany("Authorizations")
                        .HasForeignKey("AccGroupSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Function", "Function")
                        .WithMany("Authorizations")
                        .HasForeignKey("FunctionSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountGroup");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("ADAMS.Models.Feed", b =>
                {
                    b.HasOne("ADAMS.Models.Supplier", "Supplier")
                        .WithMany("Feeds")
                        .HasForeignKey("SupplierSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany("Feeds")
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.FeedingPlanDetail", b =>
                {
                    b.HasOne("ADAMS.Models.FeedingPlanMain", "Main")
                        .WithMany("Details")
                        .HasForeignKey("FPMSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("ADAMS.Models.FeedingPlanMain", b =>
                {
                    b.HasOne("ADAMS.Models.FishVariety", "FishVariety")
                        .WithMany("FeedingPlans")
                        .HasForeignKey("FVSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishVariety");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.FeedingRecord", b =>
                {
                    b.HasOne("ADAMS.Models.Feed", "Feed")
                        .WithMany("FeedingRecords")
                        .HasForeignKey("FeedSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Pond", "Pond")
                        .WithMany("FeedingRecords")
                        .HasForeignKey("PondSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.TimeZone", "TimeZone")
                        .WithMany("FeedingRecords")
                        .HasForeignKey("TimeZoneSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feed");

                    b.Navigation("Pond");

                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("ADAMS.Models.Fry", b =>
                {
                    b.HasOne("ADAMS.Models.FishVariety", "FishVariety")
                        .WithMany("Fries")
                        .HasForeignKey("FVSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany("Fries")
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FishVariety");

                    b.Navigation("Supplier");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.FryRecord", b =>
                {
                    b.HasOne("ADAMS.Models.Fry", "Fry")
                        .WithMany()
                        .HasForeignKey("FrySN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Pond", "Pond")
                        .WithMany("FryRecords")
                        .HasForeignKey("PondSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fry");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("ADAMS.Models.GrowTargetDetail", b =>
                {
                    b.HasOne("ADAMS.Models.GrowTargetMain", "Main")
                        .WithMany("Details")
                        .HasForeignKey("GTMSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("ADAMS.Models.GrowTargetMain", b =>
                {
                    b.HasOne("ADAMS.Models.FishVariety", "FishVariety")
                        .WithMany("GrowTargets")
                        .HasForeignKey("FVSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FishVariety");
                });

            modelBuilder.Entity("ADAMS.Models.HarvestRecord", b =>
                {
                    b.HasOne("ADAMS.Models.Pond", "Pond")
                        .WithMany("HarvestRecords")
                        .HasForeignKey("PondSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("ADAMS.Models.Pond", b =>
                {
                    b.HasOne("ADAMS.Models.Area", "Area")
                        .WithMany("Ponds")
                        .HasForeignKey("AreaSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADAMS.Models.Tenant", "Tenant")
                        .WithMany("Ponds")
                        .HasForeignKey("TenantSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ADAMS.Models.SamplingRecord", b =>
                {
                    b.HasOne("ADAMS.Models.Pond", "Pond")
                        .WithMany("SamplingRecords")
                        .HasForeignKey("PondSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("ADAMS.Models.AccountGroup", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("ADAMS.Models.Area", b =>
                {
                    b.Navigation("Ponds");
                });

            modelBuilder.Entity("ADAMS.Models.Feed", b =>
                {
                    b.Navigation("FeedingRecords");
                });

            modelBuilder.Entity("ADAMS.Models.FeedingPlanMain", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ADAMS.Models.FishVariety", b =>
                {
                    b.Navigation("FeedingPlans");

                    b.Navigation("Fries");

                    b.Navigation("GrowTargets");
                });

            modelBuilder.Entity("ADAMS.Models.Function", b =>
                {
                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("ADAMS.Models.GrowTargetMain", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ADAMS.Models.Pond", b =>
                {
                    b.Navigation("FeedingRecords");

                    b.Navigation("FryRecords");

                    b.Navigation("HarvestRecords");

                    b.Navigation("SamplingRecords");
                });

            modelBuilder.Entity("ADAMS.Models.Supplier", b =>
                {
                    b.Navigation("Feeds");
                });

            modelBuilder.Entity("ADAMS.Models.Tenant", b =>
                {
                    b.Navigation("AccountGroups");

                    b.Navigation("Accounts");

                    b.Navigation("Areas");

                    b.Navigation("Feeds");

                    b.Navigation("Fries");

                    b.Navigation("Ponds");
                });

            modelBuilder.Entity("ADAMS.Models.TimeZone", b =>
                {
                    b.Navigation("FeedingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
